# Site settings
title: Getting Started Guides
description: Getting Started guides for Intel IoT
author:
  name: Pearl Chen
  email: pearl@klab.ca
baseurl: ""

# Build settings
markdown: rdiscount

highlighter: pygments

exclude: ['Gemfile']
