# Site settings
title: Getting Started Guides
description: Getting Started guides for Intel IoT
author:
  name: Pearl Chen
  email: pearl@klab.ca
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

exclude: ['Gemfile']
