# Site settings
title: Getting Started Guides
description: Getting Started guides for Intel IoT
author:
  name: Pearl Chen
  email: pearl@klab.ca
baseurl: "/getting-started-guides" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM

highlighter: pygments

exclude: ['Gemfile']
