# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: git-roadshow-docs--jekyll
description: Getting Started guides for Intel IoT
author:
  name: Pearl Chen
  email: pearl@klab.ca

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: none
paginate: 0
paginate_path: 'page:num'

pygments: false

baseurl: 
